/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.quantasy.gateway.service.device.temperatureIR;

import ch.quantasy.gateway.service.device.DeviceServiceContract;
import ch.quantasy.tinkerforge.device.temperatureIR.TemperatureIRDevice;

/**
 *
 * @author reto
 */
public class TemperatureIRServiceContract extends DeviceServiceContract {

    public final String REACHED;
    public final String PERIOD;
    public final String CALLBACK_PERIOD;
    public final String THRESHOLD;

    public final String AMBIENT_TEMPERATURE;
    public final String STATUS_TOPIC_ANALOG_VALUE;
    public final String STATUS_TOPIC_AMBIENT_TEMPERATURE_THRESHOLD;
    public final String STATUS_TOPIC_AMBIENT_TEMPERATURE_CALLBACK_PERIOD;
    public final String EVENT_TOPIC_AMBIENT_TEMPERATURE;
    public final String EVENT_TOPIC_AMBIENT_TEMPERATURE_REACHED;
    public final String INTENT_TOPIC_ANALOG_VALUE;
    public final String INTENT_TOPIC_AMBIENT_TEMPERATURE_THRESHOLD;
    public final String INTENT_TOPIC_AMBIENT_TEMPERATURE_CALLBACK_PERIOD;

    public final String OBJECT_TEMPERATURE;
    public final String STATUS_TOPIC_ILLUMINANCE;
    public final String STATUS_TOPIC_OBJECT_TEMPERATURE_THRESHOLD;
    public final String STATUS_TOPIC_ILLUMINANCE_CALLBACK_PERIOD;
    public final String EVENT_TOPIC_OBJECT_TEMPERATURE;
    public final String EVENT_TOPIC_OBJECT_TEMPERATURE_REACHED;
    public final String INTENT_TOPIC_ILLUMINANCE;
    public final String INTENT_TOPIC_OBJECT_TEMPERATURE_THRESHOLD;
    public final String INTENT_TOPIC_OBJECT_TEMPERATURE_CALLBACK_PERIOD;

    public final String DEBOUNCE;
    public final String STATUS_TOPIC_DEBOUNCE;
    public final String EVENT_TOPIC_DEBOUNCE;
    public final String INTENT_TOPIC_DEBOUNCE;
    public final String INTENT_TOPIC_DEBOUNCE_PERIOD;
    public final String STATUS_TOPIC_DEBOUNCE_PERIOD;

    public TemperatureIRServiceContract(TemperatureIRDevice device) {
        super(device);

        PERIOD = "period";
        CALLBACK_PERIOD = "callbackPeriod";
        THRESHOLD = "threshold";

        REACHED = "reached";
        AMBIENT_TEMPERATURE = "ambientTemperature";
        STATUS_TOPIC_ANALOG_VALUE = STATUS_TOPIC + "/" + AMBIENT_TEMPERATURE;
        STATUS_TOPIC_AMBIENT_TEMPERATURE_THRESHOLD = STATUS_TOPIC_ANALOG_VALUE + "/" + THRESHOLD;
        STATUS_TOPIC_AMBIENT_TEMPERATURE_CALLBACK_PERIOD = STATUS_TOPIC_ANALOG_VALUE + "/" + CALLBACK_PERIOD;
        EVENT_TOPIC_AMBIENT_TEMPERATURE = EVENT_TOPIC + "/" + AMBIENT_TEMPERATURE;
        EVENT_TOPIC_AMBIENT_TEMPERATURE_REACHED = EVENT_TOPIC_AMBIENT_TEMPERATURE + "/" + REACHED;
        INTENT_TOPIC_ANALOG_VALUE = INTENT_TOPIC + "/" + AMBIENT_TEMPERATURE;
        INTENT_TOPIC_AMBIENT_TEMPERATURE_THRESHOLD = INTENT_TOPIC_ANALOG_VALUE + "/" + THRESHOLD;
        INTENT_TOPIC_AMBIENT_TEMPERATURE_CALLBACK_PERIOD = INTENT_TOPIC_ANALOG_VALUE + "/" + CALLBACK_PERIOD;

        OBJECT_TEMPERATURE = "objectTemperature";
        STATUS_TOPIC_ILLUMINANCE = STATUS_TOPIC + "/" + OBJECT_TEMPERATURE;
        STATUS_TOPIC_OBJECT_TEMPERATURE_THRESHOLD = STATUS_TOPIC_ILLUMINANCE + "/" + THRESHOLD;
        STATUS_TOPIC_ILLUMINANCE_CALLBACK_PERIOD = STATUS_TOPIC_ILLUMINANCE + "/" + CALLBACK_PERIOD;
        EVENT_TOPIC_OBJECT_TEMPERATURE = EVENT_TOPIC + "/" + OBJECT_TEMPERATURE;
        EVENT_TOPIC_OBJECT_TEMPERATURE_REACHED = EVENT_TOPIC_OBJECT_TEMPERATURE + "/" + REACHED;
        INTENT_TOPIC_ILLUMINANCE = INTENT_TOPIC + "/" + OBJECT_TEMPERATURE;
        INTENT_TOPIC_OBJECT_TEMPERATURE_THRESHOLD = INTENT_TOPIC_ILLUMINANCE + "/" + THRESHOLD;
        INTENT_TOPIC_OBJECT_TEMPERATURE_CALLBACK_PERIOD = INTENT_TOPIC_ILLUMINANCE + "/" + CALLBACK_PERIOD;

        DEBOUNCE = "debounce";
        STATUS_TOPIC_DEBOUNCE = STATUS_TOPIC + "/" + DEBOUNCE;
        STATUS_TOPIC_DEBOUNCE_PERIOD = STATUS_TOPIC_DEBOUNCE + "/" + PERIOD;
        EVENT_TOPIC_DEBOUNCE = EVENT_TOPIC + "/" + DEBOUNCE;
        INTENT_TOPIC_DEBOUNCE = INTENT_TOPIC + "/" + DEBOUNCE;
        INTENT_TOPIC_DEBOUNCE_PERIOD = INTENT_TOPIC_DEBOUNCE + "/" + PERIOD;
    }
}
